FOLD_HISTORY = []
HIGHLIGHT_FACES = []
DRAW_HANDLERS = set()

DEBUG_UV_SEGMENTS = []
INTERACTION_UV_SEGMENT_LISTS = []
DEBUG_BLOCKED_EDGES = []
DEBUG_FLOODS = []
DEBUG_TESTED_EDGES = []
DEBUG_CORNER_POINTS = []
DEBUG_CORNER_LINES = []